services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: awesome-pizza-fe:local
    ports:
      - "4200:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
